language: node_js
node_js: stable
before_script:
- bower install --silent
addons:
  sauce_connect: true
script:
- npm run lint
- polymer test --plugin sauce --job-name "google-drive-browser:${TRAVIS_BRANCH}" --build-number=${TRAVIS_BUILD_NUMBER}
cache:
  directories:
  - node_modules
branches:
  only:
  - stage
  - develop
after_success:
- node tasks/ci.js
env:
  global:
  - secure: EH3fzu18Hq3j7sgYBeGocjyBKwm/nkgybH0/qdV5Xnw4UuFbJa+OEDmUc+PS8fTkbZmxg9fhyNPeKCHojQ6f7DWGo1Gbqwpudh/wG7+Ch778Z0dVOSMMxzZx69qwmni4V2ar1xVwvzFa++L7TbtYcAuVP21Gx91fh9Vcggr9PaLp8tnnJIgIf9ua4bKZGCI2Km1R/nt/8QW/hTwFgUmA8Lbu9lXGdP9wSuWIRPHu1FrLhLYSsMsiAc5JMD/O/4Q2dzVUpHi2GVyWxtJ2J+aBGw1atuNAIVoyXYl5cmaIjwboobZd28DBAutmjmthN78tghdRq1m2JIxad3CJtti3XQZIW66uGz6kcT1+Y+s3PtoXZJm/8Xvv71Wf3+dPW3JHp17u1LnPnzDh1OdguwgXxjY4gDmEDz2FBWN4sz5Dnh+RsHdLVR2GhcZVuX7cxaHjHNSPTcuxFghWr9mqElZkSnQutalNR5BEC50ZUnYAc4hXLvbe5X23hWWc9ylaJ5M7B1KPSOZ6pB7Ar2lCrBlo4+POKS7r2zmX5251LIS6Q828jqp45TXmUoidw8TsWWnbT3flXf2UzfnwZZlIjpDj/Dx2rhQgN2Yr6ecYi5jMRvWebf5grW6hGWpbaQZAeqz3JUMAePJEQTrWgUzi4/xaelpl6a3Jm0q01TsPgX2eV2I=
  - secure: PvK87l+QMZqOk1byKT6VUypKf+lGIoToKHEk8ib6WEngT/Xi+0iVSod0H1bZApLLwZYm6tpUVBefiWK4EusanpeQ5lcry25H7Hjh6L7kTv+glqN8GrXd85PWIDSa8804QlVxLf1LKBJsOl7p8eqTt4oZWoJx4XS3nTbjYKCybbsD+ZXcjLmJvqiBDPrc6+39HjBiiNZA/ALuqXvXKN3+3uaBvEYoVJPc+DN/dkOPKwaRqpymgRC7WzZyPhfsbw64/CyoSWEIxJJqovuV5PJRJcml9i1fQQay4iv2NV5gZWLbk2YCs6ubz3nnFlC1PDmzMwnPbRdwzBJp/1trcEyL68g4qXGayJ+GFX8y3/smsOHhTqmw45khlRSBEXusOWckK+kRnlpipfj4+RKBZA22RzqWrBmZz7BchxRNVx/NKf9miNlhZIFguO3b4z9XZPXb00A/i61U3kDbTIRHxzTB1WtMiNihz55gn4GFMcwiG3rluS2ejquchdOBJm6yPa5+jTmTyOYBpeeDdLiYfmbdUf3QxuNniThgcHlUkTtmMjaoUviyk4VVVMfzEHlHy841jWTAC3tzWNzETB2RB7dwzJuc4BE7M+OOkEkoXD4Ev4xc5Q99uXVuXiQQWqT6YKL82ld5Gdf9i4uKZdqsEniO19Md8/pppWRmtKZ7XjKJOzg=
